#!/bin/bash

# Check if at least one argument is provided
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <your_input>"
    exit 1
fi

# Access the first command-line argument
input="$1"

# Text goes from 24 to 9264
#grep -n 'END OF THE PROJECT GUTENBERG EBOOK GRIMMS\|START OF THE PROJECT GUTENBERG EBOOK GRIMMS' $1


# Version 1

sed '1,120d' $1 | sed '9140,9492d' > text.txt

grep -o -n -E \
"(THE GOLDEN BIRD|HANS IN LUCK|JORINDA AND JORINDEL|THE TRAVELLING MUSICIANS|OLD SULTAN|THE STRAW, THE COAL, AND THE BEAN|BRIAR ROSE|THE DOG AND THE SPARROW|THE TWELVE DANCING PRINCESSES|THE FISHERMAN AND HIS WIFE|THE WILLOW-WREN AND THE BEAR|THE FROG-PRINCE|CAT AND MOUSE IN PARTNERSHIP|THE GOOSE-GIRL|THE ADVENTURES OF CHANTICLEER AND PARTLET|1. HOW THEY WENT TO THE MOUNTAINS TO EAT NUTS|2. HOW CHANTICLEER AND PARTLET WENT TO VISIT MR KORBES|RAPUNZEL|FUNDEVOGEL|THE VALIANT LITTLE TAILOR|HANSEL AND GRETEL|THE MOUSE, THE BIRD, AND THE SAUSAGE|MOTHER HOLLE|LITTLE RED-CAP [LITTLE RED RIDING HOOD]|THE ROBBER BRIDEGROOM|TOM THUMB|RUMPELSTILTSKIN|CLEVER GRETEL|THE OLD MAN AND HIS GRANDSON|THE LITTLE PEASANT|FREDERICK AND CATHERINE|SWEETHEART ROLAND|SNOWDROP|THE PINK|CLEVER ELSIE|THE MISER IN THE BUSH|ASHPUTTEL|THE WHITE SNAKE|THE WOLF AND THE SEVEN LITTLE KIDS|THE QUEEN BEE|THE ELVES AND THE SHOEMAKER|THE JUNIPER-TREE|THE TURNIP|CLEVER HANS|THE THREE LANGUAGES|THE FOX AND THE CAT|THE FOUR CLEVER BROTHERS|LILY AND THE LION|THE FOX AND THE HORSE|THE BLUE LIGHT|THE RAVEN|THE GOLDEN GOOSE|THE WATER OF LIFE|THE TWELVE HUNTSMEN|THE KING OF THE GOLDEN MOUNTAIN|DOCTOR KNOWALL|THE SEVEN RAVENS|THE WEDDING OF MRS FOX|FIRST STORY|SECOND STORY|THE SALAD|THE STORY OF THE YOUTH WHO WENT FORTH TO LEARN WHAT FEAR WAS|KING GRISLY-BEARD|IRON HANS|CAT-SKIN|SNOW-WHITE AND ROSE-RED)" \
text.txt| awk -F':' '{print $1 ":" "!" $2 ":"}' > stories.txt

grep -o -n -i -E \
"(darkness|destruction|dissolution|dying|extermination|grave|kill|murder|necrosis|rage|ruin|slay|slew|tomb|trouble)" \
text.txt| awk '{print $0 ","}' > grim.txt


grep -o -n -i -E \
"(being|birth|beautiful|born|essence|growth|heart|joyful|life|soul|sparkle|spirit|vigor|vitality|zest)" \
text.txt | awk '{print $0 ","}' > cheer.txt


cat stories.txt grim.txt cheer.txt| sort -n | cut -d ':' -f 2- | tr -d '\n' | tr '!' '\n' | sed 's/,$//' > results.txt




